
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: update

  profiles:
    active: dev
