spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev
    h2:
      console.enabled: true
  datasource:
    url: jdbc:h2:mem:devDb
    username: sa
    password: sa

    driverClassName: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
