spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: update
---
spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driverClassName: org.postgresql.Driver
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:devDb
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true