spring:
  datasource:
    url: jdbc:h2:mem:devDb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true